#import "../vorlage.typ": *

= Point estimation

Chapter 10 set up the language of statistical inference: a parametric statistical model $(Omega, cal(A), P_Theta)$, a #emph[statistic] $T : Omega^n -> RR^k$ computed from the observed sample, a #emph[parameter of interest] $gamma(theta)$, and the #emph[likelihood function] $L(theta | x)$. That chapter answered "what could we possibly want to infer, and from what?" This chapter answers the most basic inferential question of all: given the data, produce a single #emph[best guess] for the unknown parameter. Such a guess is called a #emph[point estimate], as opposed to the whole-interval answer of Chapter 13 or the yes/no verdict of Chapter 12.

Three questions organize the chapter. First, what #emph[is] an estimator? (Any statistic aimed at $gamma$ — so the real work is choosing a good one.) Second, how do we decide whether an estimator is good — the vocabulary of bias, variance, mean squared error, consistency and efficiency. Third, are there general recipes for #emph[constructing] good estimators rather than guessing them? — the maximum-likelihood estimator and the method of moments.

== Estimators and estimates

Throughout this chapter we fix a parametric statistical model $(Omega, cal(A), P_Theta)$ and a sample size $n in NN_(>0)$. Following common usage we write everything for the full parameter $theta$, but every statement holds verbatim when $theta$ is replaced by a parameter of interest $gamma(theta)$ derived from it. We always assume the quantity being estimated is #emph[identifiable] in the model (Chapter 10), since otherwise no amount of data could pin it down.

#definition(title: "Estimator and estimate")[
An *estimator* for a parameter of interest $gamma$ is a statistic
$
hat(gamma) = T(X_1, dots, X_n) ,
$
i.e. a measurable function of the random sample that does #emph[not] depend on the unknown $theta$. Applied to a concrete realization $x = (x_1, dots, x_n)$ it yields the *estimate* $hat(gamma)_"obs" := hat(gamma)(x) = T(x_1, dots, x_n)$, a single number (or vector). As with any statistic we assume a version exists for every $n$ and write $hat(gamma)_n$ to make the sample size explicit. Since the full parameter is itself a valid parameter of interest, $gamma(theta) = theta$, we also speak of an estimator $hat(theta)$ for $theta$.
]

The distinction is worth stressing: the *estimator* $hat(gamma)$ is a random variable (a function of the random sample), while the *estimate* $hat(gamma)_"obs"$ is the fixed number it takes on the data we actually saw. Statements about bias, variance and consistency are properties of the estimator; the estimate is what we report.

#keyfact[
#emph[Anything] measurable is a valid estimator. Nothing in the definition rules out silly choices — a constant, or a function ignoring most of the data. The definition only fixes the #emph[type] of object; deciding which estimators are #emph[good] is the entire content of the rest of this chapter.
]

#example(title: "can I win?")[
At a graduation celebration you may buy a lottery ticket to win a branded hoodie; there are $N in NN_(>0)$ winning tickets in total, but $N$ is unknown and is our parameter of interest. Drawing a ticket yourself, model its number as $X ~ "Unif"{1, dots, N}$ (uniform on the integers up to $N$). Having drawn the number $x$, what should we guess for $N$? The estimator $hat(N)(X) = X$ (just the number drawn) seems too optimistic, since you probably did not draw the largest ticket; $hat(N)(X) = 2X$ (you likely drew "somewhere in the middle") or $hat(N)(X) = X + 15$ or $hat(N)(X) = 1000$ are all equally #emph[valid] estimators. Buying three tickets $x = (x_1, x_2, x_3)$ gives more choices still: $hat(N)(x) = max{x_1, x_2, x_3}$, that maximum plus a correction, and so on. Each is a legitimate estimator; the theory below is what lets us rank them.
]

== Judging an estimator: bias, variance and MSE

To compare estimators we need numerical measures of quality. All of them are computed under the assumption that the data really were generated by $P_theta$ for the true parameter $theta$, and the expectations below are taken over that sampling distribution.

#definition(title: "Quality of an estimator")[
Let $hat(theta) = hat(theta)_n$ be an estimator for $theta in Theta$.
+ *Bias.* $"Bias"[hat(theta)] := EE[hat(theta)] - theta$. The estimator is *unbiased* if $"Bias"[hat(theta)] = 0$, i.e. $EE[hat(theta)] = theta$ for #emph[all] $theta in Theta$.
+ *Variance.* $"Var"[hat(theta)] := EE[(hat(theta) - EE[hat(theta)])^2]$; for a vector parameter this becomes the covariance matrix $"Cov"[hat(theta), hat(theta)]$.
+ *Mean squared error.* $"MSE"[hat(theta)] := EE[(hat(theta) - theta)^2]$, the average squared distance from the truth. For a vector parameter, $"MSE"[hat(theta)] = EE[||hat(theta) - theta||_2^2]$.
+ *Consistency.* $hat(theta)_n$ is *consistent* if $hat(theta)_n attach(arrow.r.long, t: "P") theta$ (convergence in probability, Chapter 9), and *strongly consistent* if $hat(theta)_n attach(arrow.r.long, t: "a.s.") theta$.
+ *Asymptotic normality.* $hat(theta)_n$ is *asymptotically normal* if there is a quantity $V(theta)$ with $sqrt(n)(hat(theta)_n - theta) attach(arrow.r.long, t: "d") cal(N)(0, V(theta))$; then $V(theta)$ is the *asymptotic variance* and, for large $n$, $hat(theta)_n approx cal(N)(theta, V(theta) \/ n)$.
+ *Efficiency.* Among all #emph[unbiased] estimators, one achieving the smallest possible variance is a *minimum variance unbiased estimator (MVUE)*.
]

Bias measures systematic error (does the estimator hit the target #emph[on average]?), variance measures spread (how much does the estimate jump around from sample to sample?), and the MSE combines both into a single number. The three are tied together by one identity you will use constantly.

#keyfact[
The *bias--variance decomposition* holds for every estimator:
$
"MSE"[hat(theta)] = EE[(hat(theta) - theta)^2] = "Var"[hat(theta)] + ("Bias"[hat(theta)])^2 .
$
So the mean squared error splits into a variance part and a squared-bias part. For an unbiased estimator the second term vanishes and $"MSE"[hat(theta)] = "Var"[hat(theta)]$.
]

#proof[
Insert and remove $EE[hat(theta)]$ inside the square and expand:
$
EE[(hat(theta) - theta)^2] = EE[((hat(theta) - EE[hat(theta)]) + (EE[hat(theta)] - theta))^2] .
$
The cross term is $2 (EE[hat(theta)] - theta) dot EE[hat(theta) - EE[hat(theta)]]$, and since $EE[hat(theta)] - theta$ is a constant while $EE[hat(theta) - EE[hat(theta)]] = 0$, it vanishes. What remains is
$
EE[(hat(theta) - EE[hat(theta)])^2] + (EE[hat(theta)] - theta)^2 = "Var"[hat(theta)] + ("Bias"[hat(theta)])^2 .
$
]

#remark[
The decomposition is often read as an inherent #emph[bias--variance trade-off]: simple estimators (few parameters) tend to have large bias but small variance ("underfitting"), while complex ones reduce bias at the cost of higher variance ("overfitting"). This intuition is useful but not a law: it fails, for example, in the heavily overparameterized models of modern machine learning, where one can drive down bias #emph[and] variance — and hence the MSE — simultaneously. What is always true is the algebraic identity above; the practical goal, especially in machine learning, is to minimize the MSE, not any single term.
]

Two properties deserve emphasis because they are easy to confuse. #emph[Unbiasedness] is a statement about a single sample size ($EE[hat(theta)_n] = theta$), whereas #emph[consistency] is a statement about the limit ($hat(theta)_n -> theta$ as $n -> oo$). Neither implies the other, as the examples below show.

== Worked examples: sample mean and sample variance

The sample mean is the estimator against which all others are measured, and it behaves impeccably.

#example(title: "properties of the sample mean")[
Let $X_1, dots, X_n$ be i.i.d. with mean $mu$ and finite variance $sigma^2 > 0$ (the underlying distribution need #emph[not] be Gaussian). Consider $hat(mu) = bar(X)_n = frac(1,n) sum_(i=1)^n X_i$ as an estimator for $gamma(theta) = mu$.
- *Unbiased:* by linearity, $EE[bar(X)_n] = frac(1,n) sum_(i=1)^n EE[X_i] = mu$, so $"Bias"[bar(X)_n] = 0$.
- *Strongly consistent:* the weak and strong laws of large numbers (Chapter 9) give $bar(X)_n attach(arrow.r.long, t: "P") mu$ and $bar(X)_n attach(arrow.r.long, t: "a.s.") mu$.
- *Variance:* by independence, $"Var"[bar(X)_n] = frac(1, n^2) sum_(i=1)^n "Var"[X_i] = sigma^2 \/ n$, which shrinks as $n$ grows.
- *MSE:* being unbiased, $"MSE"[bar(X)_n] = "Var"[bar(X)_n] = sigma^2 \/ n$.
- *Asymptotically normal:* the central limit theorem gives $sqrt(n)(bar(X)_n - mu) attach(arrow.r.long, t: "d") cal(N)(0, sigma^2)$, so the asymptotic variance is $V(theta) = sigma^2$.
The sample mean is efficient (an MVUE) in the Gaussian model, but need not be efficient for other distributions.
]

For the variance the situation is subtler, and explains the mysterious "$n - 1$".

#example(title: "the sample variance and Bessel's correction")[
With $X_1, dots, X_n$ i.i.d. of mean $mu$ and variance $sigma^2$, define the *sample variance*
$
S_n^2 := frac(1, n - 1) sum_(i=1)^n (X_i - bar(X)_n)^2
quad "and the naive estimator" quad
hat(sigma)^2 := frac(1, n) sum_(i=1)^n (X_i - bar(X)_n)^2 .
$
The key algebraic identity is
$
sum_(i=1)^n (X_i - bar(X)_n)^2 = sum_(i=1)^n (X_i - mu)^2 - n (bar(X)_n - mu)^2 .
$
Taking expectations and using $EE[(X_i - mu)^2] = sigma^2$ and $EE[(bar(X)_n - mu)^2] = "Var"[bar(X)_n] = sigma^2 \/ n$,
$
EE[sum_(i=1)^n (X_i - bar(X)_n)^2] = n sigma^2 - n dot frac(sigma^2, n) = (n - 1) sigma^2 .
$
Dividing by $n - 1$ therefore gives $EE[S_n^2] = sigma^2$: the sample variance is *unbiased* in any model — this division by $n - 1$ is *Bessel's correction*. The naive estimator instead has $EE[hat(sigma)^2] = frac(n - 1, n) sigma^2 < sigma^2$, so it is biased and systematically underestimates the variance. Both are consistent, since the correction factor tends to $1$.
]

Whether $S_n^2$ is actually the #emph[better] estimator is a separate question — its unbiasedness costs variance, and for normal data one can show $"Var"[S_n^2] = 2 sigma^4 \/ (n - 1)$ while the biased $hat(sigma)^2$ has strictly smaller MSE. This is a textbook case where accepting a little bias buys a large enough reduction in variance to lower the overall MSE.

Finally, a pair of examples showing that unbiasedness and consistency are genuinely independent.

#example(title: "biased-but-consistent vs. unbiased-but-inconsistent")[
Let $X_1, dots, X_n$ be i.i.d. with mean $mu$ and variance $sigma^2 > 0$.
- *Biased but consistent:* $hat(mu)_n := bar(X)_n + frac(1, n)$ has $EE[hat(mu)_n] = mu + frac(1, n) != mu$, so it is biased for every finite $n$. Yet $bar(X)_n attach(arrow.r.long, t: "P") mu$ and $frac(1, n) -> 0$, so $hat(mu)_n attach(arrow.r.long, t: "P") mu$ is consistent.
- *Unbiased but not consistent:* $tilde(mu)_n := X_1$ (ignore all but the first observation) has $EE[tilde(mu)_n] = mu$, hence is unbiased for every $n$. But it never concentrates — $"Var"[tilde(mu)_n] = sigma^2 > 0$ does not vanish — so $tilde(mu)_n$ does #emph[not] converge to $mu$ and is inconsistent.
]

== The maximum-likelihood estimator

So far we have judged estimators handed to us. We now want a general procedure that #emph[constructs] one. The most important such recipe reuses the likelihood function of Chapter 10: pick the parameter under which the observed data were most probable.

#definition(title: "Maximum-likelihood estimator (MLE)")[
The *maximum-likelihood estimator* $hat(theta)_"mle"$ is the value of $theta$ that maximizes the likelihood, equivalently the log-likelihood:
$
hat(theta)_"mle" (x) in arg max_(theta in Theta) L(theta | x) = arg max_(theta in Theta) ell(theta | x) ,
$
the two agreeing because $ell = ln L$ and $ln$ is strictly increasing. If $ell(theta | x)$ is differentiable and the maximum lies in the interior of $Theta$, the MLE is found among the solutions of the *likelihood equation* $nabla_theta ell(theta | x) = 0$.
]

#keyfact[
The MLE recipe, for an i.i.d. sample: (1) write the likelihood as the product $L(theta | x) = product_(i=1)^n p(x_i | theta)$ of per-observation pmfs/densities; (2) take logs to turn the product into the sum $ell(theta | x) = sum_(i=1)^n ln p(x_i | theta)$; (3) differentiate, set $nabla_theta ell = 0$, and solve for $theta$; (4) check it is a maximum (e.g. a negative second derivative). The logarithm is what makes step (3) tractable.
]

=== Worked example: Bernoulli

#example(title: "MLE for a Bernoulli / Binomial proportion")[
Let $X_1, dots, X_n$ be i.i.d. $"Ber"(p)$ with $x_i in {0, 1}$ and pmf $p(x_i | p) = p^(x_i) (1 - p)^(1 - x_i)$. The likelihood collects the exponents:
$
L(p | x) = product_(i=1)^n p^(x_i) (1 - p)^(1 - x_i) = p^(sum_(i=1)^n x_i) (1 - p)^(n - sum_(i=1)^n x_i) .
$
Writing $s = sum_(i=1)^n x_i$ for the number of successes, the log-likelihood is
$
ell(p | x) = s ln p + (n - s) ln(1 - p) .
$
Differentiating and setting to zero,
$
frac(partial ell, partial p) = frac(s, p) - frac(n - s, 1 - p) = 0
quad ==> quad
(1 - p) s = p (n - s)
quad ==> quad
hat(p)_"mle" = frac(s, n) = frac(1, n) sum_(i=1)^n x_i = bar(x)_n .
$
The second derivative $-s \/ p^2 - (n - s) \/ (1 - p)^2 < 0$ confirms a maximum. The MLE is simply the observed success frequency — and since the number of successes in $n$ i.i.d. Bernoulli trials is $"Bin"(n, p)$, this is exactly the MLE for the Binomial proportion as well.
]

=== Worked example: Poisson

#example(title: "MLE for a Poisson rate")[
Let $X_1, dots, X_n$ be i.i.d. $"Poi"(lambda)$ with pmf $p(x_i | lambda) = e^(-lambda) lambda^(x_i) \/ x_i !$. The likelihood and log-likelihood are
$
L(lambda | x) = product_(i=1)^n e^(-lambda) frac(lambda^(x_i), x_i !) = e^(-n lambda) frac(lambda^(sum_(i=1)^n x_i), product_(i=1)^n x_i !) ,
quad
ell(lambda | x) = -n lambda + (sum_(i=1)^n x_i) ln lambda - sum_(i=1)^n ln(x_i !) .
$
The final sum does not depend on $lambda$, so it drops out on differentiation:
$
frac(partial ell, partial lambda) = -n + frac(1, lambda) sum_(i=1)^n x_i = 0
quad ==> quad
hat(lambda)_"mle" = frac(1, n) sum_(i=1)^n x_i = bar(x)_n .
$
Since $partial^2 ell \/ partial lambda^2 = - (sum_(i=1)^n x_i) \/ lambda^2 < 0$, this is a maximum. The MLE of the Poisson rate is the sample mean.
]

=== Worked example: Gaussian mean and variance

#example(title: [MLE for a Normal $cal(N)(mu, sigma^2)$])[
For $X_1, dots, X_n$ i.i.d. $cal(N)(mu, sigma^2)$, the per-observation density $p(x_i | mu, sigma^2) = (2 pi sigma^2)^(-1 \/ 2) exp(- (x_i - mu)^2 \/ (2 sigma^2))$ gives log-likelihood
$
ell(mu, sigma^2 | x) = - frac(n, 2) ln(2 pi) - frac(n, 2) ln(sigma^2) - frac(1, 2 sigma^2) sum_(i=1)^n (x_i - mu)^2 .
$
This is a two-parameter maximization. The partial derivatives are
$
frac(partial ell, partial mu) = frac(1, sigma^2) (sum_(i=1)^n x_i - n mu) ,
quad
frac(partial ell, partial sigma^2) = - frac(n, 2 sigma^2) + frac(1, 2 (sigma^2)^2) sum_(i=1)^n (x_i - mu)^2 .
$
Setting $partial ell \/ partial mu = 0$ yields $hat(mu)_"mle" = bar(x)_n$; substituting this into $partial ell \/ partial sigma^2 = 0$ yields
$
hat(mu)_"mle" = frac(1, n) sum_(i=1)^n x_i = bar(x)_n ,
quad
hat(sigma)^2_"mle" = frac(1, n) sum_(i=1)^n (x_i - bar(x)_n)^2 .
$
The MLE of the mean coincides with the (unbiased) sample mean, but the MLE of the variance is the #emph[naive] estimator $hat(sigma)^2$ from before — it divides by $n$, not $n - 1$, and is therefore biased.
]

The pattern across these derivations is summarized in the following table of maximum-likelihood estimators for the standard i.i.d. models (no closed form need exist in general — sometimes the MLE must be found numerically).

#table(
  columns: 3,
  [*Model*], [*Parameter*], [*Maximum-likelihood estimator*],
  [$"Ber"(p)$], [$p$], [$bar(X)_n$],
  [$"Poi"(lambda)$], [$lambda$], [$bar(X)_n$],
  [$"Exp"(lambda)$], [$lambda$], [$1 \/ bar(X)_n$],
  [$cal(N)(mu, sigma^2)$], [$(mu, sigma^2)$], [$(bar(X)_n, thin frac(1, n) sum_(i=1)^n (X_i - bar(X)_n)^2)$],
  [$"Unif"(0, theta)$], [$theta$], [$X_((n)) = max_i X_i$],
)

=== Properties of the MLE

The MLE gives no free guarantees at finite $n$ (the Gaussian variance case shows it can be biased). Its appeal is asymptotic: under mild regularity conditions — which hold for the common models and which we assume throughout — it behaves optimally as $n -> oo$.

#remark[
Under regularity conditions, the maximum-likelihood estimator is
+ *consistent:* $hat(theta)_"mle" attach(arrow.r.long, t: "P") theta$;
+ *asymptotically normal:* $sqrt(n)(hat(theta)_"mle" - theta) attach(arrow.r.long, t: "d") cal(N)(0, V(theta))$ with $V(theta) = cal(I)(theta)^(-1)$, the inverse Fisher information (below);
+ *asymptotically efficient:* it attains the smallest possible asymptotic variance in a large class of estimators;
+ *invariant:* if $hat(theta)_"mle"$ estimates $theta$ and $g$ is a function, then $g(hat(theta)_"mle")$ is the MLE of $g(theta)$ — e.g. the MLE of the standard deviation is $sqrt(hat(sigma)^2_"mle")$.
]

The MLE is not sacred: it can be biased, and it need not be the minimum-variance choice for finite $n$. The uniform model shows both how the MLE arises and how it can be beaten.

#example(title: [MVUE for $"Unif"(0, theta)$])[
Let $X_1, dots, X_n$ be i.i.d. $"Unif"(0, theta)$ with $Theta = RR_(>0)$. The likelihood $L(theta | x) = theta^(-n)$ for $theta >= max_i x_i$ (and $0$ otherwise) is decreasing in $theta$, so it is maximized at the smallest admissible value: the MLE is the sample maximum $hat(theta)_"mle" = X_((n)) = max_i X_i$. Its sampling density is $f_(X_((n)))(y) = n y^(n - 1) \/ theta^n$ on $[0, theta]$, from which
$
EE[X_((n))] = integral_0^theta y frac(n y^(n - 1), theta^n) dif y = frac(n, n + 1) theta < theta ,
$
so the MLE is #emph[biased] (it can never exceed the true $theta$). Rescaling removes the bias: $hat(theta)_2 := frac(n + 1, n) X_((n))$ satisfies $EE[hat(theta)_2] = theta$. Using $EE[X_((n))^2] = frac(n, n + 2) theta^2$ one finds
$
"Var"[hat(theta)_2] = frac(theta^2, n (n + 2)) ,
$
which for $n > 1$ beats the moment-style unbiased estimator $hat(theta)_1 := 2 bar(X)_n$ with $"Var"[hat(theta)_1] = theta^2 \/ (3 n)$, since $n(n + 2) > 3 n$. In fact $hat(theta)_2$ is the unique MVUE for $theta$ — a reminder that the sample mean, though often good, is sometimes not the best.
]

#remark[
That "unbiased and minimum-variance" is not the final word is dramatized by the *James--Stein estimator*. For a single observation $X ~ cal(N)(mu, I_d)$ in dimension $d >= 3$, the natural (unbiased, and also maximum-likelihood) estimator $hat(mu)(X) = X$ has $"MSE" = d$, yet the biased shrinkage estimator $hat(mu)_"js" = (1 - (d - 2) \/ ||X||^2) X$, which pulls the estimate toward the origin, has strictly smaller MSE for #emph[every] $mu$. Introducing bias can pay off even when it seems there is nothing to gain.
]

== The method of moments

Maximum likelihood is one general construction procedure; a second, older and often simpler, is the *method of moments*. The idea: the theoretical moments $EE[X^j]$ are functions of $theta$, and the law of large numbers says the empirical moments $frac(1, n) sum_(i=1)^n X_i^j$ estimate them. So we express $theta$ through the moments and plug in the empirical ones.

#definition(title: "Method-of-moments estimator")[
Suppose $theta in RR^k$. Equate the first $k$ theoretical moments to the corresponding sample moments,
$
EE[X^j] = frac(1, n) sum_(i=1)^n X_i^j , quad j = 1, dots, k ,
$
and solve the resulting system for $theta$. The solution $hat(theta)_"mom"$ is the *method-of-moments estimator*.
]

#example(title: "method of moments for common models")[
- *Poisson.* Here $EE[X] = lambda$, so the single equation $lambda = bar(X)_n$ gives $hat(lambda)_"mom" = bar(X)_n$ — identical to the MLE.
- *Exponential.* Here $EE[X] = 1 \/ lambda$, so $1 \/ lambda = bar(X)_n$ gives $hat(lambda)_"mom" = 1 \/ bar(X)_n$ — again the MLE.
- *Normal.* Two parameters need two moments: $EE[X] = mu$ and $EE[X^2] = mu^2 + sigma^2$. The first gives $hat(mu)_"mom" = bar(X)_n$; the second gives
$
hat(sigma)^2_"mom" = frac(1, n) sum_(i=1)^n X_i^2 - bar(X)_n^2 = frac(1, n) sum_(i=1)^n (X_i - bar(X)_n)^2 ,
$
the same (biased) variance estimate as the MLE.
]

The method of moments and maximum likelihood often coincide, but not always; when they differ, moment estimators are typically easier to compute while MLEs typically have better efficiency.

== Efficiency, Fisher information and the Cramér--Rao bound

We have used the word "efficient" informally. There is a hard lower bound on how small the variance of an unbiased estimator can be, governed by a single quantity that measures how much a sample tells us about $theta$.

#definition(title: "Fisher information")[
For a model with log-likelihood $ell(theta | x)$, the *Fisher information* is
$
cal(I)(theta) = EE[ (frac(partial, partial theta) ell(theta | x))^2 ] = - EE[ frac(partial^2, partial theta^2) ell(theta | x) ] ,
$
the variance of the *score* $frac(partial, partial theta) ell$ (the two forms agreeing under regularity conditions). It quantifies how much information the observable $X$ carries about $theta$.
]

#theorem(name: "Cramér--Rao lower bound")[
Under regularity conditions, every unbiased estimator $hat(theta)$ of $theta$ satisfies
$
"Var"[hat(theta)] >= frac(1, cal(I)(theta)) .
$
]

An unbiased estimator that #emph[attains] this bound is called *efficient*; an efficient estimator is automatically an MVUE. The converse can fail: an MVUE may exist even when no estimator reaches the Cramér--Rao bound, which is exactly why the search for good estimators remains a rich subject. The construction of MVUEs rests on the notion of a *sufficient statistic* (one that captures all the information about $theta$ in the sample): the *Rao--Blackwell theorem* improves any unbiased estimator by conditioning it on a sufficient statistic. A more restrictive cousin is the *best linear unbiased estimator (BLUE)*, the minimum-variance estimator among #emph[linear] ones; the *Gauss--Markov theorem* states that ordinary least squares is BLUE for linear regression. These optimal-estimator results, together with the maximum-likelihood and moment recipes above, form the classical toolkit of point estimation — the foundation on which the interval estimates of Chapter 13 and the Bayesian alternative of Chapter 14 build.

#quizblock(title: "Quiz — Point estimation")[
#question[Define the bias of an estimator $hat(theta)$ and state the bias--variance decomposition of its mean squared error. What does the decomposition say for an unbiased estimator?]
#answer[The bias is $"Bias"[hat(theta)] = EE[hat(theta)] - theta$, and $hat(theta)$ is unbiased if this is $0$ for all $theta$. The decomposition is $"MSE"[hat(theta)] = EE[(hat(theta) - theta)^2] = "Var"[hat(theta)] + ("Bias"[hat(theta)])^2$. For an unbiased estimator the squared-bias term is $0$, so $"MSE"[hat(theta)] = "Var"[hat(theta)]$.]

#question[Let $X_1, dots, X_n$ be i.i.d. with mean $mu$ and variance $sigma^2 > 0$, and let $hat(mu) = bar(X)_n$. Compute its bias, variance and MSE, and say why it is (strongly) consistent.]
#answer[By linearity $EE[bar(X)_n] = mu$, so the bias is $0$. By independence $"Var"[bar(X)_n] = sigma^2 \/ n$, and since it is unbiased $"MSE"[bar(X)_n] = "Var"[bar(X)_n] = sigma^2 \/ n$. The strong law of large numbers gives $bar(X)_n attach(arrow.r.long, t: "a.s.") mu$, hence also convergence in probability, so $bar(X)_n$ is strongly consistent.]

#question[Derive the maximum-likelihood estimator of $p$ for an i.i.d. Bernoulli sample $X_1, dots, X_n ~ "Ber"(p)$.]
#answer[With $s = sum_i x_i$, the likelihood is $L(p | x) = p^s (1 - p)^(n - s)$, so $ell(p | x) = s ln p + (n - s) ln(1 - p)$. Setting $frac(partial ell, partial p) = frac(s, p) - frac(n - s, 1 - p) = 0$ gives $(1 - p) s = p(n - s)$, i.e. $hat(p)_"mle" = s \/ n = bar(x)_n$. The negative second derivative confirms a maximum, so the MLE is the observed success frequency.]

#question[For an i.i.d. Poisson sample, show that the maximum-likelihood estimator and the method-of-moments estimator of $lambda$ coincide.]
#answer[MLE: $ell(lambda | x) = -n lambda + (sum_i x_i) ln lambda - sum_i ln(x_i !)$, and $frac(partial ell, partial lambda) = -n + frac(1, lambda) sum_i x_i = 0$ gives $hat(lambda)_"mle" = bar(x)_n$. Method of moments: $EE[X] = lambda$, so equating to the first sample moment $bar(X)_n$ gives $hat(lambda)_"mom" = bar(X)_n$. Both equal the sample mean.]

#question[Why does the sample variance divide by $n - 1$? Show that $EE[S_n^2] = sigma^2$ while the naive estimator $hat(sigma)^2 = frac(1, n) sum_i (X_i - bar(X)_n)^2$ is biased.]
#answer[Using $sum_i (X_i - bar(X)_n)^2 = sum_i (X_i - mu)^2 - n(bar(X)_n - mu)^2$ and taking expectations, $EE[sum_i (X_i - bar(X)_n)^2] = n sigma^2 - n(sigma^2 \/ n) = (n - 1)sigma^2$. Dividing by $n - 1$ gives $EE[S_n^2] = sigma^2$ (unbiased — Bessel's correction), whereas dividing by $n$ gives $EE[hat(sigma)^2] = frac(n - 1, n) sigma^2 < sigma^2$, so the naive estimator underestimates the variance.]

#question[For $X_1, dots, X_n ~ "Unif"(0, theta)$, what is the MLE of $theta$? Is it unbiased, and how would you correct it?]
#answer[The likelihood $theta^(-n)$ (valid for $theta >= max_i x_i$) is decreasing in $theta$, so the MLE is the sample maximum $hat(theta)_"mle" = X_((n))$. It is biased: $EE[X_((n))] = frac(n, n + 1) theta < theta$, since the maximum can never exceed $theta$. Rescaling to $hat(theta)_2 = frac(n + 1, n) X_((n))$ gives an unbiased estimator (indeed the MVUE), with $"Var"[hat(theta)_2] = theta^2 \/ (n(n + 2))$.]

#question[Give an estimator that is unbiased but not consistent, and one that is biased but consistent, for a mean $mu$ (i.i.d. data, variance $sigma^2 > 0$).]
#answer[Unbiased but inconsistent: $tilde(mu)_n = X_1$, since $EE[X_1] = mu$ yet $"Var"[X_1] = sigma^2$ never vanishes, so it does not converge to $mu$. Biased but consistent: $hat(mu)_n = bar(X)_n + frac(1, n)$, since $EE[hat(mu)_n] = mu + frac(1, n) != mu$ but $bar(X)_n attach(arrow.r.long, t: "P") mu$ and $frac(1, n) -> 0$ give $hat(mu)_n attach(arrow.r.long, t: "P") mu$.]

#question[What is a minimum-variance unbiased estimator (MVUE), and what does the Cramér--Rao bound say about the variance of any unbiased estimator?]
#answer[An MVUE is an unbiased estimator with the smallest possible variance among all unbiased estimators of the parameter. The Cramér--Rao bound states that any unbiased estimator $hat(theta)$ satisfies $"Var"[hat(theta)] >= 1 \/ cal(I)(theta)$, where $cal(I)(theta)$ is the Fisher information. An unbiased estimator attaining this bound is called efficient and is in particular an MVUE.]
]
